### ISSUE TITLE
Pull Issue Summary from JIRA

### ISSUE THREAD

**Issue by kevinmoilar** [sephii/taxi#108]
As a developer I would like to type taxi start SUP-5681on my CLI to populate the timesheet description with the issue summary from JIRA, in order to save time and save my PO the headache of fixing my timesheets.

**Comment by sephii** [comment]
I like the idea, however this will be hard to do technically because Jira doesn't track anything about Zebra, so there's no way in getting the Zebra alias from a given Jira ticket. We could fix this by adding a custom field in Jira that would be the Zebra alias that should be use for every ticket, but then it would be a lot of work on the PO side to set this field for every ticket.

Even if we did this, the hardest part would be logging in to Jira, since we don't have any Jira login information yet, we would need to allow the user to set this somewhere and handle Jira authentication.

**Comment by gnutix** [comment]
This issue may get some inspiration from the https://github.com/alexandreblin/taxi-tempo repository ? To avoid having "work on the PO side", I decided to generate a bunch of taxi aliases for JIRA tickets from a static range, like `SUP-[0-5000]`, so I can use `SUP-521   09:00-12:00   Doing something` in my timesheet entries. Not sure how far that would get along with the current state of taxi / zebra though.

This issue should probably be moved to https://github.com/sephii/taxi-zebra too.

**Comment by sephii** [comment]
Thanks for the input. I don’t have any use for this at the moment, feel free to reopen it if anyone needs this.
