### ISSUE TITLE
Allow using character other than # for commented lines

### ISSUE THREAD

**Issue by colinfrei** [sephii/taxi#60]
I edit my taxi file with a markdown editor. That editor recognizes lines starting with a # as headers, and displays them like that. It would be cool to use a different character at the beginning of the line (maybe *;* ?) for commented lines, or to make that configurable.

**Comment by sephii** [comment]
I think this is related to https://github.com/sephii/taxi/issues/72.

It would be cool to take it one step further and use these characters to set flags on entries. These characters could then be edited in the config. For example the currently "flags" used in taxi are "pushed" (which is not a flag yet since commented entries are ignored) and "ignored" (when you add a question mark at the end of the alias). The user could then set in her configuration file:

```
[flags]
pushed = ;
ignored = ?
```

**Comment by colinfrei** [comment]
yep, seems related!
Only thing to keep in mind is that you currently have flags in different places. I don't know if it makes sense to only allow them at the beginning of a line or not.

**Comment by sephii** [comment]
Let's continue this discussion on #72. I suggest we close this one if the approach proposed in #72 would meet your needs.

**Comment by colinfrei** [comment]
Fine for me!
